### ISSUE TITLE
OCaml highlighter

### ISSUE THREAD

**Issue by NathanFallet** [markusressel/KodeHighlighter#18]
See https://github.com/ccampbell/rainbow/issues/254

**Comment by NathanFallet** [comment]
@markusressel Can this lexer using regex help to implement an OCaml highlighter? https://github.com/GroupeMINASTE/OCaml-iOS/blob/main/OCaml/Models/OCamlLexer.swift

**Comment by markusressel** [comment]
Yes it should be, KodeHighlighter also used regex for lexing.

**Comment by NathanFallet** [comment]
@markusressel Just opened #20 to fix the issue!
